/**
 * @dmb/ui-kit — the Dispatch design system.
 *
 * Brutalist primitives (atoms) generated by shadcn and rethemed to the reference
 * design: 0 radius, ink borders that scale with the control, solid offset
 * shadows, a single #FFE600 accent. Space Grotesk for prose, Space Mono for
 * anything that behaves like a control.
 *
 * These are *primitives only*. Nothing in here knows what a Message, a Tag, or a
 * User is — domain components live in features/ and consume these. See CLAUDE.md
 * for the boundary.
 */

// Actions
export { Button, buttonVariants } from "./components/button"

// Form controls
export { Input, inputVariants } from "./components/input"
export { Textarea } from "./components/textarea"
export { Label } from "./components/label"
export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from "./components/select"
export { ToggleGroup, ToggleGroupItem } from "./components/toggle-group"
export { Toggle, toggleVariants } from "./components/toggle"
export {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
} from "./components/field"

// Date
export { Calendar, CalendarDayButton } from "./components/calendar"
export {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "./components/popover"

// Display
export { Badge, badgeVariants } from "./components/badge"
export {
  Avatar,
  avatarVariants,
  AvatarBadge,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarImage,
} from "./components/avatar"
export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./components/card"
export { Separator } from "./components/separator"

// Feedback / states
export { Skeleton } from "./components/skeleton"
export { Spinner } from "./components/spinner"
export {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "./components/empty"

// Utilities
export { cn } from "./lib/utils"
